### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by martinjo** [szk-atmosphere/SABlurImageViewObjc#6]
It seems that SABlurImageViewObjc never deallocates. In my projects memory is leaked as soon as I use the [imageView startBlurAnimation:duration] method. I'm not completely sure what is causing the leak, but if I stick to using the [imageView blur:] method then everything deallocates as expected.

**Comment by marty-suzuki** [comment]
Hi, @martinjo
Thank you for your report!

I've fix memory leak for startBlurAnimation.
Please update pod below code.

``` ruby
pod "SABlurImageViewObjc", :git => "https://github.com/szk-atmosphere/SABlurImageViewObjc.git", :tag => "0.2.0"
```

Thank you
